// <auto-generated />
namespace Brewgr.Web.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class hopcountry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hopcountry));
        
        string IMigrationMetadata.Id
        {
            get { return "201703142350405_hopcountry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
